[package]
name = "gridentify"
version = "0.1.0"
authors = ["Hytak <lhc.holten@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
lto = true

[lib]
name = "gridentify"
crate-type = ["cdylib"]

[dependencies]
array-init = "0.1.1"
rand = "0.7.3"
serde_json = "1.0.44"
serde = "1.0.104"

[dependencies.pyo3]
version = "0.8.5"
features = ["extension-module"]

[dependencies.rusqlite]
version = "0.21.0"
features = ["bundled"]